export const BREAKPOINT = {
  sm: 540,
  md: 768,
  lg: 1104,
}

export const LEASE_TERM_IN_DAYS = 14

export const MAIL = 'mailto:hi@matters.town'

export const ERROR = {
  // General
  CHAIN_NOT_SET: 'CHAIN_NOT_SET',
  CONTRACT_NOT_SET: 'CONTRACT_NOT_SET',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  // Board related
  BOARD_ID_NOT_SET: 'BOARD_ID_NOT_SET',
  BOARD_NOT_FOUND: 'BOARD_NOT_FOUND',

  // Claim related
  ROUNDS_NOT_FOUND: 'ROUNDS_NOT_FOUND',
  ROUNDS_IS_EMPTY: 'ROUNDS_IS_EMPTY',
  TREE_NOT_FOUND: 'TREE_NOT_FOUND',
  TREE_IS_EMPTY: 'TREE_IS_EMPTY',
  DIST_NOT_FOUND: 'DIST_NOT_FOUND',
  DIST_IS_EMPTY: 'DIST_IS_EMPTY',
}
