export const BREAKPOINTS = {
  sm: 540,
  md: 768,
  lg: 1104,
}

export const MAIL = 'mailto:hi@matters.town'

export const ERROR = {
  CONTRACT_NOT_SET: 'CONTRACT_NOT_SET',
  ROUNDS_DATA_NOT_FOUND: 'ROUNDS_DATA_NOT_FOUND',
  ROUNDS_DATA_IS_EMPTY: 'ROUNDS_DATA_IS_EMPTY',
  TREE_DATA_NOT_FOUND: 'TREE_DATA_NOT_FOUND',
  TREE_DATA_IS_EMPTY: 'TREE_DATA_IS_EMPTY',
  DIST_DATA_IS_EMPTY: 'DIST_DATA_IS_EMPTY',
  INVALID_ADDRESS: 'WRONG_ADDRESS',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
}
