
name: Billboard Rounds - Create PR to update latest round
on: workflow_dispatch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install @aws-sdk/client-s3 ## the only dependency for ./bin/sync-up-latest-round.mjs

      - run: ./bin/sync-up-latest-round.mjs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BILLBOARD_GITHUB_TOKEN }}
          commit-message: Update report
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto/round3-assets
          delete-branch: true
          add-paths: |
            public/static
          ## title: '[Example] Update preview Assets'
          title: check in latest round Assets from 'Create or Update Request' action
          body: |
            Update preview Assets
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: true
